/**
 * Central catalogue of business error codes.
 * Every failure that can reach the user MUST use one of these codes so the UI
 * can show a consistent Arabic message (see messages.ar.ts).
 */
export const ErrorCode = {
  // Generic
  INTERNAL: 'INTERNAL',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  RATE_LIMITED: 'RATE_LIMITED',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',

  // Catalogue / inventory
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  VARIANT_NOT_AVAILABLE: 'VARIANT_NOT_AVAILABLE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  STOCK_BELOW_RESERVED: 'STOCK_BELOW_RESERVED',

  // Orders
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_LOCKED: 'ORDER_LOCKED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ORDER_TOO_LARGE: 'ORDER_TOO_LARGE',
  EMPTY_ORDER: 'EMPTY_ORDER',

  // Accounting
  PAYMENT_INVALID: 'PAYMENT_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

